### ISSUE TITLE
Win64 compilation

### ISSUE THREAD

**Issue by Olgierd-1** [alexeydott/DelphiLibPROJ#1]
Hi,
I have a problem to use the library for win64 application.
When I try to compile the (win64) project, I get the error: 'E1026 File not found: PJ_eqearth.o'. I chacked it and I can't find the file. Could you please send my the required file?

Regards
Olgierd

**Comment by alexeydott** [comment]
hi. i`v updated files in repo including obj/o. now everything should work. also i added c-sources and bat-files to build them. now you can build the obj files yourself.

**Comment by Olgierd-1** [comment]
Thank you for the update. I see that there is a lot of changes. 

Regords
Olgierd
